name: 'Steel Bank Common Lisp'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lisp:
          - sbcl-bin
    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install sbcl;
      - run: cd Assignment_2; sbcl --script Assignment6.lisp;
